version: "3"
services:
  hdsearch:
    image: mklean/baseline-microsuite:hdsearch_router_setalgebra_recommend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    ports:
        - "50050:50050"
        - "50051:50051"
        - "50052:50052"
        - "50053:50053"
        - "50054:50054"
        - "11211:11211"
