version: "3"
services:
  hdsearch:
    image: msuite-hdsearch-test:latest
    volumes:
        - /home/tsazei01/shared_datasets/HDSearch/image_feature_vectors.dat
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    ports:
        - "50050:50050"
        - "50051:50051"
        - "50052:50052"
        - "50053:50053"
        - "50054:50054"
        - "11211:11211"

    environment:
        http_proxy: http://proxy.cs.ucy.ac.cy:8008
        https_proxy: http://proxy.cs.ucy.ac.cy:8008
        no_proxy: localhost,127.0.0.1 

